version: "3.8"

services:
  mongo:
    image: mongo

    ports:
      - 27027:27017

    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
     -v /home/wishrohitv/desktop/data:/data/db

